// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxA13IYatLEs1bUc9euSi-Kk0zQo7lNKM',
    appId: '1:912693915409:web:4017489b02db1ba2b5a6b0',
    messagingSenderId: '912693915409',
    projectId: 'reddit-clone-1676a',
    authDomain: 'reddit-clone-1676a.firebaseapp.com',
    storageBucket: 'reddit-clone-1676a.firebasestorage.app',
  );
  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFrnfQB9hirn1tXmFON1-JCCEGaZMwSg',
    appId: '1:912693915409:android:2bd8e8365027f296b5a6b0',
    messagingSenderId: '912693915409',
    projectId: 'reddit-clone-1676a',
    storageBucket: 'reddit-clone-1676a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmzwaVoAazuTmF58i3F6DkVR6oY4EjjQ',
    appId: '1:912693915409:ios:b7280a6c8d005440b5a6b0',
    messagingSenderId: '912693915409',
    projectId: 'reddit-clone-1676a',
    storageBucket: 'reddit-clone-1676a.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxA13IYatLEs1bUc9euSi-Kk0zQo7lNKM',
    appId: '1:912693915409:web:f41b2fd3472aab77b5a6b0',
    messagingSenderId: '912693915409',
    projectId: 'reddit-clone-1676a',
    authDomain: 'reddit-clone-1676a.firebaseapp.com',
    storageBucket: 'reddit-clone-1676a.firebasestorage.app',
  );
}
